include: "https://gitlab.gnome.org/GNOME/citemplates/raw/master/flatpak/flatpak_ci_initiative.yml"

flatpak:
  image: "registry.gitlab.gnome.org/gnome/gnome-runtime-images/gnome:master"
  variables:
    MANIFEST_PATH: "app.drey.Blurble.Devel.json"
    FLATPAK_MODULE: "blurble"
    APP_ID: "app.drey.Blurble.Devel"
    RUNTIME_REPO: "https://nightly.gnome.org/gnome-nightly.flatpakrepo"
    BUNDLE: "blurble-dev.flatpak"
  extends: ".flatpak"

nightly:
  extends: ".publish_nightly"
  needs:
    - "flatpak"
